[[quote]]
text = "If debugging is the process of removing software bugs, then programming must be the process of putting them in"
author = "Edsger W. Dijkstra"
theme = "Cyberspace"
probability = 5

[[quote]]
text = "Object-oriented programming is an exceptionally bad idea which could only have originated in California."
author = "Edsger W. Dijkstra"
theme = "Cyberspace"
probability = 5

[[quote]]
text = "The use of COBOL cripples the mind; its teaching should, therefore, be regarded as a criminal offense"
author = "Edsger W. Dijkstra"
theme = "Cyberspace"
probability = 5

[[quote]]
text = "Computer science is no more about computers than astronomy is about telescopes"
author = "Edsger W. Dijkstra"
theme = "Cyberspace"
probability = 5

[[quote]]
text = "It is practically impossible to teach good programming to students that have had a prior exposure to BASIC: as potential programmers they are mentally mutilated beyond hope of regeneration"
author = "Edsger W. Dijkstra"
theme = "Cyberspace"
probability = 5
